# Generated by Django 5.0.6 on 2025-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_create_default_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageimage",
            name="masking_params",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
