# Generated by Django 5.0.6 on 2025-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_pageimage_masking_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientencounter",
            name="record_ipno",
            field=models.CharField(
                help_text="Hospital IPNO number", max_length=50, unique=True
            ),
        ),
    ]
