# Generated by Django 5.0.6 on 2025-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_patientencounter_record_ipno"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTaskMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(db_index=True, max_length=100)),
                ("task_id", models.CharField(max_length=255, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("template", "Template Detection"),
                            ("align", "Alignment"),
                            ("extract", "AI Extraction"),
                            ("upload", "AI Upload"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction Task Map",
                "verbose_name_plural": "Transaction Task Maps",
                "indexes": [
                    models.Index(
                        fields=["transaction_id", "task_type"],
                        name="api_transac_transac_f2c7b1_idx",
                    )
                ],
            },
        ),
    ]
